datasource.url=jdbc:postgresql://localhost:5432/pharmacy
datasource.username=macbookpro
datasource.password=19801980
datasource.driver-class-name=org.postgresql.Driver
application.root-path=/Users/macbookpro/Documents/pdp/spring-core-g54/src/main/resources/store
application.domen=http://localhost:8080